'use client'

import Link from 'next/link'
import { useQuery } from '@tanstack/react-query'
import { createClient } from '@/lib/supabase/client'
import type { Customer, Quote } from '@/types'
import { Button } from '@/components/ui/Button'
import { cn } from '@/lib/utils'

// There is no direct "create an order" action — orders only exist as the
// output of converting a quote (see quotes/[id]/page.tsx `convertMutation`).
// Before this page existed, /dashboard/orders/new fell through to the
// dynamic [id] route with id="new", which produced 400s from Postgres
// (invalid uuid) on every query and left the page stuck on "Loading…"
// forever. This route intercepts that literal path and instead does the
// one useful thing a user landing here actually wants: get to a quote they
// can convert, or start a new one.
const STATUS_STYLES: Record<string, string> = {
  draft: 'bg-gray-100 text-gray-700',
  sent: 'bg-blue-100 text-blue-700',
}

export default function NewOrderPage() {
  const supabase = createClient()

  const { data: quotes, isLoading } = useQuery({
    queryKey: ['quotes', 'convertible'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('quotes')
        .select('*')
        .in('status', ['draft', 'sent'])
        .order('created_at', { ascending: false })
      if (error) throw error
      return data as Quote[]
    },
  })

  const { data: customers } = useQuery({
    queryKey: ['customers'],
    queryFn: async () => {
      const { data, error } = await supabase.from('customers').select('*')
      if (error) throw error
      return data as Customer[]
    },
  })

  const customerName = (id: string) => customers?.find((c) => c.id === id)?.name ?? '—'

  return (
    <div className="max-w-2xl">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">New order</h1>
        <p className="mt-1 text-sm text-gray-500">
          Orders aren&apos;t created directly — they&apos;re generated by converting a quote, so pricing, margin, and
          cost snapshots always trace back to a quoted line. Pick a quote below to convert, or start a new one.
        </p>
      </div>

      <div className="mb-6 overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div className="border-b border-gray-200 px-4 py-3">
          <h2 className="font-semibold text-gray-900">Quotes ready to convert</h2>
        </div>
        <table className="min-w-full divide-y divide-gray-200 text-sm">
          <thead className="bg-gray-50 text-left text-xs font-semibold uppercase text-gray-500">
            <tr>
              <th className="px-4 py-3">Customer</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3">Created</th>
              <th className="px-4 py-3" />
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {isLoading && <tr><td className="px-4 py-6 text-gray-500" colSpan={4}>Loading…</td></tr>}
            {!isLoading && quotes?.length === 0 && (
              <tr>
                <td className="px-4 py-6 text-gray-500" colSpan={4}>
                  No draft or sent quotes to convert yet.
                </td>
              </tr>
            )}
            {quotes?.map((q) => (
              <tr key={q.id} className="hover:bg-gray-50">
                <td className="px-4 py-3 font-medium text-gray-900">{customerName(q.customer_id)}</td>
                <td className="px-4 py-3">
                  <span className={cn('rounded-full px-2 py-0.5 text-xs font-semibold capitalize', STATUS_STYLES[q.status])}>
                    {q.status}
                  </span>
                </td>
                <td className="px-4 py-3 text-gray-600">{new Date(q.created_at).toLocaleDateString()}</td>
                <td className="px-4 py-3 text-right">
                  <Link href={`/dashboard/quotes/${q.id}`} className="font-medium text-brand-600 hover:underline">
                    Open &amp; convert
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="flex flex-wrap gap-3">
        <Link href="/dashboard/quotes/new">
          <Button>New quote</Button>
        </Link>
        <Link href="/dashboard/quotes">
          <Button variant="secondary">View all quotes</Button>
        </Link>
        <Link href="/dashboard/orders">
          <Button variant="ghost">Back to orders</Button>
        </Link>
      </div>
    </div>
  )
}
